---
- name: Add Zabbix repository
  yum:
    name: "https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm"
    state: present

- name: Install Zabbix agent
  yum:
    name: zabbix-agent
    state: present

- name: Deploy Zabbix agent configuration file
  template:
    src: zabbix_agentd.conf.yml
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart zabbix-agent

- name: Validate Zabbix agent configuration
  command: zabbix_agentd -p
  register: zabbix_conf_check
  changed_when: false
  failed_when: "'OK' not in zabbix_conf_check.stdout"

- name: Show validation result
  debug:
    msg: "{{ zabbix_conf_check.stdout }}"


- name: Open firewall port (10050/tcp)
  firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled
  notify:
    - reload firewalld

- name: Start and enable Zabbix agent service
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
